name: Deploy su Aruba via FTP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Installa lftp
        run: sudo apt-get install -y lftp

      - name: Deploy su Aruba
        env:
          FTP_USER: ${{ secrets.FTP_USERNAME }}
          FTP_PASS: ${{ secrets.FTP_PASSWORD }}
        run: |
          echo "machine ftp.autoscuolasanbiagio.com login $FTP_USER password $FTP_PASS" > ~/.netrc
          chmod 600 ~/.netrc
          lftp -e "
            set ssl:verify-certificate no;
            set ftp:passive-mode on;
            set net:timeout 60;
            set net:max-retries 3;
            open ftp.autoscuolasanbiagio.com;
            cd www.autoscuolasanbiagio.com;
            put -O . $GITHUB_WORKSPACE/index.html;
            put -O . $GITHUB_WORKSPACE/privacy.html;
            bye
          "
